import {Inter} from 'next/font/google';
import './globals.css';

const inter = Inter({
    variable: '--inter-font',
    subsets: ['latin']
});
export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

interface RootLayoutProps {
    children: React.ReactNode
}

export default function RootLayout(props: RootLayoutProps) {
    return (
        <html lang="en" className={inter.variable}>
        <body>{props.children}</body>
        </html>
    )
}
